### ISSUE TITLE
robustness - tests

### ISSUE THREAD

**Issue by livneido1** [AyalaBadash/market_2022#283]

**Comment by livneido1** [comment]
check all cases where services are down and what so ever:

- [x] test for acquisition where the service is down 
- [x] test init where a service is down
- [x] test when acquisition is canceled, the cart doesn't change 
- [ ] test that a member receive a notification for service down (only real time )
- [ ]

**Comment by BARDAMRI** [comment]
test that a member receive a notification for service down (only real time ) cannot happened without the member to do some action with this service. This because the services has no continues  connection to the market. so we have no way to keep check when they are available. This is why the is handshake method in the payment service to check connection before.
What is the meaning.
All of the other test exists
